In [149]:
import pandas as pd
df=pd.read_csv('data/raw/bank/bank-.csv')

In [150]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45209 non-null  str
 4   default    45208 non-null  str
 5   balance    45210 non-null  float64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45210 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45203 non-null  float64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  Target     45205 non-null  str
dtypes: float64(3), int64(4), str(10)
memory usage: 5.9 MB

In [151]:
df.head()

   age           job  marital  education  ... pdays  previous poutcome Target
0   58    management  married   tertiary  ...  -1.0         0  unknown     no
1   44    technician   single  secondary  ...  -1.0         0  unknown     no
2   33  entrepreneur  married  secondary  ...  -1.0         0  unknown     no
3   47   blue-collar  married    unknown  ...  -1.0         0  unknown     no
4   33       unknown   single    unknown  ...  -1.0         0  unknown     no

[5 rows x 17 columns]

In [152]:
df.isnull().sum()

age          0
job          0
marital      0
education    2
default      3
balance      1
housing      0
loan         0
contact      0
day          0
month        0
duration     1
campaign     0
pdays        8
previous     0
poutcome     0
Target       6
dtype: int64

In [153]:
#missing value
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df.fillna({col:df[col].mode()[0]},inplace=True)
            else:
                df.fillna({col:df[col].mean()},inplace=True)
    return df

In [154]:
df=toldir(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  float64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  float64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  Target     45211 non-null  str
dtypes: float64(3), int64(4), str(10)
memory usage: 5.9 MB

In [155]:
df.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
Target       False
dtype: bool

In [156]:
df.nunique()

age            77
job            12
marital         3
education       4
default         2
balance      7169
housing         2
loan            2
contact         3
day            31
month          12
duration     1574
campaign       48
pdays         560
previous       41
poutcome        4
Target          2
dtype: int64

In [157]:
#Encoding
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
encoder=LabelEncoder()
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=3:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [158]:
df=encodla(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                45211 non-null  int64
 1   job                45211 non-null  int64
 2   education          45211 non-null  int64
 3   balance            45211 non-null  float64
 4   day                45211 non-null  int64
 5   month              45211 non-null  int64
 6   duration           45211 non-null  float64
 7   campaign           45211 non-null  int64
 8   pdays              45211 non-null  float64
 9   previous           45211 non-null  int64
 10  poutcome           45211 non-null  int64
 11  marital_divorced   45211 non-null  int64
 12  marital_married    45211 non-null  int64
 13  marital_single     45211 non-null  int64
 14  default_no         45211 non-null  int64
 15  default_yes        45211 non-null  int64
 16  housing_no         45211 non-null  int64
 17  housing_yes        45211 non-null  int64
 18  loan_no            45211 non-null  int64
 19  loan_yes           45211 non-null  int64
 20  contact_cellular   45211 non-null  int64
 21  contact_telephone  45211 non-null  int64
 22  contact_unknown    45211 non-null  int64
 23  Target_no          45211 non-null  int64
 24  Target_yes         45211 non-null  int64
dtypes: float64(3), int64(22)
memory usage: 8.6 MB

In [161]:
#Scaling
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('age')
def scaling(df):

    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [162]:
df=scaling(df)
df.head()

   age       job  education  ...  contact_unknown  Target_no  Target_yes
0   58  0.363636   0.666667  ...              1.0        1.0         0.0
1   44  0.818182   0.333333  ...              1.0        1.0         0.0
2   33  0.181818   0.333333  ...              1.0        1.0         0.0
3   47  0.090909   1.000000  ...              1.0        1.0         0.0
4   33  1.000000   1.000000  ...              1.0        1.0         0.0

[5 rows x 25 columns]

# Linear Regression

In [163]:
#Model selection
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [174]:
#Training
x=df.drop('age',axis=1)

In [175]:
y=df['age']

In [176]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [177]:
x_train.shape

(36168, 24)

In [178]:
y_train.shape

(36168,)

In [179]:
lr.fit(x_train,y_train)

LinearRegression()

In [180]:
#Prediction
y_pred=lr.predict(x_test)
y_pred[0]

np.float64(41.71457724993818)

In [181]:
#Evaluation
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [182]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [183]:
print('r2: ',r2)
print('mae: ',mae)
print('mse: ',mse)

r2:  0.2590053545424218
mae:  7.340611158759769
mse:  83.57743284957434

# Lasso Regression

In [29]:
df=pd.read_csv('data/raw/bank/bank-.csv')

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45209 non-null  str
 4   default    45208 non-null  str
 5   balance    45210 non-null  float64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45210 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45203 non-null  float64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  Target     45205 non-null  str
dtypes: float64(3), int64(4), str(10)
memory usage: 5.9 MB

In [31]:
toldir(df)

       age           job   marital  education  ...  pdays  previous poutcome Target
0       58    management   married   tertiary  ...   -1.0         0  unknown     no
1       44    technician    single  secondary  ...   -1.0         0  unknown     no
2       33  entrepreneur   married  secondary  ...   -1.0         0  unknown     no
3       47   blue-collar   married    unknown  ...   -1.0         0  unknown     no
4       33       unknown    single    unknown  ...   -1.0         0  unknown     no
...    ...           ...       ...        ...  ...    ...       ...      ...    ...
45206   51    technician   married   tertiary  ...   -1.0         0  unknown    yes
45207   71       retired  divorced    primary  ...   -1.0         0  unknown    yes
45208   72       retired   married  secondary  ...  184.0         3  success    yes
45209   57   blue-collar   married  secondary  ...   -1.0         0  unknown     no
45210   37  entrepreneur   married  secondary  ...  188.0        11    other     no

[45211 rows x 17 columns]

In [32]:
df=toldir(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  float64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  float64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  Target     45211 non-null  str
dtypes: float64(3), int64(4), str(10)
memory usage: 5.9 MB

In [184]:
df=encodla(df)
df=scaling(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                45211 non-null  int64
 1   job                45211 non-null  float64
 2   education          45211 non-null  float64
 3   balance            45211 non-null  float64
 4   day                45211 non-null  float64
 5   month              45211 non-null  float64
 6   duration           45211 non-null  float64
 7   campaign           45211 non-null  float64
 8   pdays              45211 non-null  float64
 9   previous           45211 non-null  float64
 10  poutcome           45211 non-null  float64
 11  marital_divorced   45211 non-null  float64
 12  marital_married    45211 non-null  float64
 13  marital_single     45211 non-null  float64
 14  default_no         45211 non-null  float64
 15  default_yes        45211 non-null  float64
 16  housing_no         45211 non-null  float64
 17  housing_yes        45211 non-null  float64
 18  loan_no            45211 non-null  float64
 19  loan_yes           45211 non-null  float64
 20  contact_cellular   45211 non-null  float64
 21  contact_telephone  45211 non-null  float64
 22  contact_unknown    45211 non-null  float64
 23  Target_no          45211 non-null  float64
 24  Target_yes         45211 non-null  float64
dtypes: float64(24), int64(1)
memory usage: 8.6 MB

In [185]:
from sklearn.linear_model import Lasso

In [186]:
lasso=Lasso(alpha=0.1)

In [187]:
x=df.drop('age',axis=1)

In [188]:
y=df['age']

In [189]:
from sklearn.model_selection import train_test_split

In [190]:
lasso

Lasso(alpha=0.1)

In [191]:
lasso.fit(x_train,y_train)

Lasso(alpha=0.1)

In [192]:
y_pred=lasso.predict(x_test)

In [193]:
#Evaluation
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [194]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [195]:
print('r2: ',r2)
print('mae: ',mae)
print('mse: ',mse)

r2:  0.24657460802206566
mae:  7.3993090982859115
mse:  84.97950759997093

# Ridge Regression

In [196]:
df=pd.read_csv('data/raw/bank/bank-.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45209 non-null  str
 4   default    45208 non-null  str
 5   balance    45210 non-null  float64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45210 non-null  float64
 12  campaign   45211 non-null  int64
 13  pdays      45203 non-null  float64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  Target     45205 non-null  str
dtypes: float64(3), int64(4), str(10)
memory usage: 5.9 MB

In [197]:
df=toldir(df)
df=encodla(df)
df=scaling(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                45211 non-null  int64
 1   job                45211 non-null  float64
 2   education          45211 non-null  float64
 3   balance            45211 non-null  float64
 4   day                45211 non-null  float64
 5   month              45211 non-null  float64
 6   duration           45211 non-null  float64
 7   campaign           45211 non-null  float64
 8   pdays              45211 non-null  float64
 9   previous           45211 non-null  float64
 10  poutcome           45211 non-null  float64
 11  marital_divorced   45211 non-null  float64
 12  marital_married    45211 non-null  float64
 13  marital_single     45211 non-null  float64
 14  default_no         45211 non-null  float64
 15  default_yes        45211 non-null  float64
 16  housing_no         45211 non-null  float64
 17  housing_yes        45211 non-null  float64
 18  loan_no            45211 non-null  float64
 19  loan_yes           45211 non-null  float64
 20  contact_cellular   45211 non-null  float64
 21  contact_telephone  45211 non-null  float64
 22  contact_unknown    45211 non-null  float64
 23  Target_no          45211 non-null  float64
 24  Target_yes         45211 non-null  float64
dtypes: float64(24), int64(1)
memory usage: 8.6 MB

In [198]:
from sklearn.linear_model import Ridge

In [199]:
ridge=Ridge(alpha=0.1)

In [200]:
x=df.drop('age',axis=1)

In [201]:
y=df['age']

In [202]:
from sklearn.model_selection import train_test_split

In [203]:
ridge

Ridge(alpha=0.1)

In [204]:
ridge.fit(x_train,y_train)

Ridge(alpha=0.1)

In [205]:
y_pred=ridge.predict(x_test)

In [206]:
#Evaluation
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [207]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [208]:
print('r2: ',r2)
print('mae: ',mae)
print('mse: ',mse)

r2:  0.25902024557910663
mae:  7.340599049528066
mse:  83.5757532765488

# RandomForest

In [209]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()

In [210]:
x=df.drop('age',axis=1)

In [211]:
y=df['age']

In [212]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [213]:
y_pred=rf.predict(x_test)

In [214]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [215]:
print('r2: ',r2)
print('mae: ',mae)
print('mse: ',mse)

r2:  0.4322079222497448
mae:  6.412718677430056
mse:  64.0417640553774

# DecisionTree

In [216]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()

In [217]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [218]:
y_pred=dt.predict(x_test)

In [219]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [220]:
print('r2: ',r2)
print('mae: ',mae)
print('mse: ',mse)

r2:  -0.12257311350320377
mae:  8.695676213645914
mse:  126.61600132699326

In [221]:
from sklearn.model_selection import KFold,cross_val_score

In [222]:
kf=KFold(n_splits=10,shuffle=True,random_state=42)

In [223]:
scores=cross_val_score(lr,x,y,cv=kf,scoring='r2')

In [224]:
print(scores)

[0.2524531  0.2647834  0.25572956 0.25459937 0.2445712  0.25438132
 0.26633674 0.25722798 0.25804221 0.26429526]

In [226]:
import numpy as np

In [228]:
np.mean(scores)

np.float64(0.2572420140098376)

In [229]:
np.std(scores)

np.float64(0.0062523038658864865)

# Tabulate

In [230]:
from tabulate import tabulate

In [231]:
results=[
    ['linear regression',0.2590,7.3406,83.5774],
    ['lasso regression', 0.24657,7.3993,84.9795],
    ['ridge regression', 0.25902,7.3405,83.5757],
    ['random forest', 0.4322,6.4127,64.0417],
    ['decisiontree', 0.1225,8.6956,126.616]
]
headers=['Algorithm','r2_score','mae','mse']
table=tabulate(results,headers=headers,tablefmt='grid')
print(table)

+-------------------+------------+--------+----------+
| Algorithm         |   r2_score |    mae |      mse |
+===================+============+========+==========+
| linear regression |    0.259   | 7.3406 |  83.5774 |
+-------------------+------------+--------+----------+
| lasso regression  |    0.24657 | 7.3993 |  84.9795 |
+-------------------+------------+--------+----------+
| ridge regression  |    0.25902 | 7.3405 |  83.5757 |
+-------------------+------------+--------+----------+
| random forest     |    0.4322  | 6.4127 |  64.0417 |
+-------------------+------------+--------+----------+
| decisiontree      |    0.1225  | 8.6956 | 126.616  |
+-------------------+------------+--------+----------+